name: Auto Deploy Next.js App on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    #almost over just go on my brother
      # 1️⃣ Checkout repo (optional, but good for reference)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ SSH into VPS and deploy
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DB_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Navigate to your app folder
            cd apps/bazenga/e_mauzo_web

            # Pull latest code from GitHub
            git reset --hard
            git clean -fd
            git pull origin main

            # Stop and remove old container if exists
            docker stop bazenga_pos || true
            docker rm bazenga_pos || true

            # Build Docker image
            docker build \
              -t bazenga_pos:latest .

            # Run container with secrets injected from GitHub
            docker run -d \
              --name bazenga_pos \
              -p 3000:3000 \
              --restart unless-stopped \
              -e NEXT_PUBLIC_HOST="${{ secrets.NEXT_PUBLIC_HOST }}" \
              bazenga_pos:latest